#!/usr/bin/bash
# Boot-menu and presentation identity.
#
# The GRUB/BLS entry title is generated by ostree at deployment time as
# "${PRETTY_NAME} (ostree:N)", read from /usr/lib/os-release. Inherited from the
# base it reads "Fedora Linux 44.x (Forty Four)", which says nothing about which
# image a machine actually booted -- the one question a boot menu exists to
# answer when there are two deployments and one of them is broken.
#
# Only the *presentation* fields change here. ID, NAME, VERSION_ID and ID_LIKE
# are deliberately left alone: downstream tooling parses those to identify the
# base, and this is Fedora 44 with our layers on top. Claiming otherwise would
# break that identification for a cosmetic gain -- the same reasoning the
# fastfetch config records for why its OS row still says Fedora.
#
# VARIANT and VARIANT_ID are the fields the os-release spec provides for exactly
# this case, so the image is identifiable without lying about the base.
set -euxo pipefail

osr=/usr/lib/os-release
test -f "${osr}"

# Take VERSION verbatim so the title keeps the base's version and date, which
# is what distinguishes two deployments in the menu.
version="$(grep -oP '(?<=^VERSION=").*(?="$)' "${osr}")"

sed -i \
    -e "s|^PRETTY_NAME=.*|PRETTY_NAME=\"ScorchedBlue ${version}\"|" \
    -e '/^VARIANT=/d' \
    -e '/^VARIANT_ID=/d' \
    "${osr}"

cat >>"${osr}" <<'VARIANT'
VARIANT="ScorchedBlue"
VARIANT_ID=scorchedblue
VARIANT

### Assertions ---------------------------------------------------------------
# A boot menu that still says Fedora is the failure this script exists to
# prevent, and it is invisible until the machine next reboots.
grep -q '^PRETTY_NAME="ScorchedBlue ' "${osr}"
grep -q '^VARIANT_ID=scorchedblue$' "${osr}"

# The base must remain identifiable. If any of these moved, something rewrote
# more than it should have.
grep -q '^ID=fedora$' "${osr}"
grep -q '^VERSION_ID=44$' "${osr}"

echo "OK: boot identity is $(grep -oP '(?<=^PRETTY_NAME=").*(?="$)' "${osr}")"
